### PR TITLE
Fix logToStdout when logPath is also set

### LINKED ISSUE #120: Log to stdout broken
## Description

The logic to log to stdout is broken when also providing a path for the log files.
We need to check here:
https://github.com/wooga/atlas-unity/blob/3db30d5377e8a888ef2a323798d73ae7fbf2e883/src/main/groovy/wooga/gradle/unity/UnityTask.groovy#L116-L119

If `logToStdout` is present and `true` to not set a log file path. Otherwise unity is not printing to stdout

### PR DESCRIPTION
**Pull request by Azurelol**
## Description

When loggin both to stdout and to a file the parameter for the `-logFile` flag must be set to `-` 
not the filepath. The internal logic will read the stdout and both print it to stdout and 
to the provided file.

resolves #120 

## Changes
* ![FIX] UnityTask: -logFile being set when logToStdout was true

[NEW]:https://atlas-resources.wooga.com/icons/icon_new.svg "New"
[ADD]:http://resources.atlas.wooga.com/icons/icon_add.svg "Add"
[IMPROVE]:http://resources.atlas.wooga.com/icons/icon_improve.svg "IMPROVE"
[CHANGE]:http://resources.atlas.wooga.com/icons/icon_change.svg "Change"
[FIX]:http://resources.atlas.wooga.com/icons/icon_fix.svg "Fix"
[UPDATE]:http://resources.atlas.wooga.com/icons/icon_update.svg "Update"

[BREAK]:http://resources.atlas.wooga.com/icons/icon_break.svg "Remove"
[REMOVE]:http://resources.atlas.wooga.com/icons/icon_remove.svg "Remove"
[IOS]:http://resources.atlas.wooga.com/icons/icon_iOS.svg "iOS"
[ANDROID]:http://resources.atlas.wooga.com/icons/icon_android.svg "Android"
[WEBGL]:http://resources.atlas.wooga.com/icons/icon_webGL.svg "Web:GL"

### CODE REVIEW

File: src/integrationTest/groovy/wooga/gradle/unity/UnityTaskIntegrationSpec.groovy [hunk 1]
```diff
@@ -467,6 +467,7 @@ abstract class UnityTaskIntegrationSpec<T extends UnityTask> extends UnityIntegr
         result.standardOutput.contains(mockUnityStartupMessage)
     }
 
+    // TODO: This test is incorrect since the assumption is wrong?
```
Comment (Larusso) [inline src/integrationTest/groovy/wooga/gradle/unity/UnityTaskIntegrationSpec.groovy:470]: This inflicts two different things. One is the flag `-logFile` provided to unity to instruct Unity to either save to file or write to stdout. When we want both! Then we need to instruct to send to stdout and the plugin will write it to the file.

Here a truth table as reference

## Unity >= 2019
| logPath set | logToStdout set | is log written to file? | flag set in unity cli |
| ----------- | --------------- | ----------------------- | --------------------- |
| :yes:       | :no:            | :yes:                   | `-logFile {path}`     |
| :yes:       | :yes:           | :yes:			  | `-logFile -`          |
| :no:        | :yes:           | :no:                    | `-logFile -`          |
| :no:        | :no:            | :no:                    | ``                    |

## Unity <= 2018 
| logPath set | logToStdout set | is log written to file? | flag set in unity cli |
| ----------- | --------------- | ----------------------- | --------------------- |
| :yes:       | :no:            | :yes:                   | `-logFile {path}`     |
| :yes:       | :yes:           | :yes:			  | `-logFile`            |
| :no:        | :yes:           | :no:                    | `-logFile`            |
| :no:        | :no:            | :no:                    | ``                    |

Comment (Azurelol) [reply src/integrationTest/groovy/wooga/gradle/unity/UnityTaskIntegrationSpec.groovy:470]: Ah sorry;  I didn't mean to commit that comment.

Comment (Larusso) [reply src/integrationTest/groovy/wooga/gradle/unity/UnityTaskIntegrationSpec.groovy]: I was unsure if we cover this in the tests correctly. What I see is only one part. But not the combination of flag and if the file is written or not and if the stdout has the correct values. I guess we added this before already or?

Comment (Azurelol) [reply src/integrationTest/groovy/wooga/gradle/unity/UnityTaskIntegrationSpec.groovy]: There's a few tests above that check for stdout. would you take a look? 
We could perhaps write another one instead?

Comment (Azurelol) [reply src/integrationTest/groovy/wooga/gradle/unity/UnityTaskIntegrationSpec.groovy]: Though I see now that test isn't function since that property is no longer there.

Comment (Azurelol) [reply src/integrationTest/groovy/wooga/gradle/unity/UnityTaskIntegrationSpec.groovy]: I am not sure if the table is correct for cases 4, 8. 
Even if no log file is set, the plugin still sets one by convention.

**Review by Larusso — APPROVED** [review]
